# This rule is not used by the project pocketoperated itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the baas.pb.simplified.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pocketoperated
    app.kubernetes.io/managed-by: kustomize
  name: pocketbase-editor-role
rules:
- apiGroups:
  - baas.pb.simplified
  resources:
  - pocketbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baas.pb.simplified
  resources:
  - pocketbases/status
  verbs:
  - get
