# This rule is not used by the project pocketoperated itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to baas.pb.simplified resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pocketoperated
    app.kubernetes.io/managed-by: kustomize
  name: pocketbase-viewer-role
rules:
- apiGroups:
  - baas.pb.simplified
  resources:
  - pocketbases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baas.pb.simplified
  resources:
  - pocketbases/status
  verbs:
  - get
